config/routes.rb
Tmap::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root :to => 'pages#index'

  resources :inquiries do
  	member do
  		get 'result'
  	end
  end
  
  resources :questions
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :question_id, :answer
  belongs_to :inquiry
  belongs_to :question

  def tags
    if answer
      return question.antitags.split(',').map { |t| t.strip }
    end
    return []
  end
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  attr_accessible :email, :answers_attributes, :classification
  attr_accessible :lon, :lat, :x, :y

  after_create :after_create_hook

  has_many :answers
  accepts_nested_attributes_for :answers

  @@classifications = [
    "residential",
    "commercial",
    "industrial",
  ]

  @@grid = [
    (1..6).to_a,
    (1..6).to_a,
    (1..6).to_a
  ]

  def self.grid
    @@grid
  end

  def self.classifications
    @@classifications
  end

  def land
    l = Land.where(x: x, y: y).first
    # XXX: Create land if it doesn't exist yet.
    if l.nil?
      l = Land.create(x: x, y: y)
    end
    return l
  end

  def tags
    ts = answers.map { |a| a.tags }.flatten
  end

  def result
    tags & land.parsed_tags
  end

  private
  def after_create_hook
    update_attributes(lon: land.random_lon,
                      lat: land.random_lat)
  end
end

app/models/land.rb
class Land < ActiveRecord::Base
  attr_accessible :earthquake, :flooding, :landslide, :tags, :tsunami, :x, :y,
    :floor_limit

  @@min_lon = 1445000
  @@max_lon = 1460000

  @@min_lat = 12130000
  @@max_lat = 12160000

  def random_lon
    diff = (@@max_lon - @@min_lon) / 3
    (@@min_lon..@@max_lon - (x * diff)).to_a.sample / 100000.0
  end

  def random_lat
    diff = (@@max_lat - @@min_lat) / 6
    (@@min_lat + (y * diff)..@@max_lat).to_a.sample / 100000.0
  end

  def parsed_tags
    unless tags.nil?
      return tags.split(',').map { |t| t.strip }
    end
    return []
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer_id, :question, :user_id, :antitags
  has_many :answers
end

app/models/reason.rb
class Reason < ActiveRecord::Base
  attr_accessible :tag, :text
end

app/models/terrain.rb
class Terrain < ActiveRecord::Base

  #Hardcoded for now, save to database later - Ardee
  @@tags = [
    [nil, nil, nil, nil, ["E","R"], ["E","R"]],
    ["T", "R", ["FO", "R"], "R", ["FI","R"], "E"],
    ["T", "X", "X", ["FO","R"],"R", nil]
  ]

  def self.tags
    @@tags
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new(x: params[:x], y: params[:y])
    Question.all.each do |q|
      @inquiry.answers.build(question_id: q.id)
    end
  end

  def create
    @inquiry = Inquiry.new(params[:inquiry])
    @inquiry.save

    # TODO: Redirect to page 3
    redirect_to result_inquiry_path(@inquiry)
  end
  
  def result
    @inquiry = Inquiry.find(params[:id])
    @safety_display = !@inquiry.result.any? ? "Yes." : "No."
    @reasons = @inquiry.result.map { |r| Reason.find_by_tag(r) }
    #@reasons = @inquiry.result
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @grid = Inquiry.grid
    @tags = Terrain.tags
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def display_tag(tag)
		if tag.nil?
			"&nbsp;".html_safe
		elsif tag.kind_of?(Array)			
			tag.join(",") 
		else
			tag
		end
	end
end

app/views/inquiries/new.html.haml
= semantic_form_for @inquiry do |f|
  = f.inputs do
    = f.input :email
    = f.input :x, as: :hidden
    = f.input :y, as: :hidden
    = f.input :classification, label: "Building Classification", as: :select, collection: options_for_select(Inquiry.classifications, Inquiry.classifications.first)

    = f.semantic_fields_for :answers do |a|
      = a.input :answer, as: :radio, label: "#{a.object.question.question}"
      = a.input :question_id, as: :hidden
  = f.submit

app/views/inquiries/result.html.haml
%div.result
  %h1= @safety_display

  %h2 Lon: #{@inquiry.lon} Lat: #{@inquiry.lat}
  = link_to "Google Maps", "http://maps.google.com/maps?z=17&t=m&q=loc:#{@inquiry.lon}+#{@inquiry.lat}"

  %ul#reasons
    - @reasons.each do |r|
      /= r
      - unless r.nil?
        %li.reason
          = r.text

app/views/inquiry/_form.html.haml
= form_for @inquiry, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :x, :class => 'control-label'
    .controls
      = f.number_field :x, :class => 'number_field'
  .control-group
    = f.label :y, :class => 'control-label'
    .controls
      = f.number_field :y, :class => 'number_field'
  .control-group
    = f.label :classification, :class => 'control-label'
    .controls
      = f.text_field :classification, :class => 'text_field'
  .control-group
    = f.label :lon, :class => 'control-label'
    .controls
      = f.text_field :lon, :class => 'text_field'
  .control-group
    = f.label :lat, :class => 'control-label'
    .controls
      = f.text_field :lat, :class => 'text_field'
  .control-group
    = f.label :land_id, :class => 'control-label'
    .controls
      = f.number_field :land_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), inquiry_path, :class => 'btn'

app/views/inquiry/edit.html.haml
- model_class = Inquiry
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/inquiry/index.html.haml
- model_class = Inquiry
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:x)
      %th= model_class.human_attribute_name(:y)
      %th= model_class.human_attribute_name(:classification)
      %th= model_class.human_attribute_name(:lon)
      %th= model_class.human_attribute_name(:lat)
      %th= model_class.human_attribute_name(:land_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @inquiries.each do |inquiry|
      %tr
        %td= link_to inquiry.id, inquiry_path(inquiry)
        %td= inquiry.email
        %td= inquiry.x
        %td= inquiry.y
        %td= inquiry.classification
        %td= inquiry.lon
        %td= inquiry.lat
        %td= inquiry.land_id
        %td=l inquiry.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_inquiry_path(inquiry), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), inquiry_path(inquiry), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_inquiry_path, :class => 'btn btn-primary'

app/views/inquiry/new.html.haml
- model_class = Inquiry
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/inquiry/show.html.haml
- model_class = Inquiry
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @inquiry.email
%p
  %strong= model_class.human_attribute_name(:x) + ':'
  %br
  = @inquiry.x
%p
  %strong= model_class.human_attribute_name(:y) + ':'
  %br
  = @inquiry.y
%p
  %strong= model_class.human_attribute_name(:classification) + ':'
  %br
  = @inquiry.classification
%p
  %strong= model_class.human_attribute_name(:lon) + ':'
  %br
  = @inquiry.lon
%p
  %strong= model_class.human_attribute_name(:lat) + ':'
  %br
  = @inquiry.lat
%p
  %strong= model_class.human_attribute_name(:land_id) + ':'
  %br
  = @inquiry.land_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), inquiry_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_inquiry_path(@inquiry), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), inquiry_path(@inquiry), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %link(href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css')
    %title= content_for?(:title) ? yield(:title) : "Tmap"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"


  %body.tmap
    #wrap
      .navbar.navbar-fluid-top
        .navbar-inner
          .container-fluid
            %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.brand(href="/") TMAP - Tayuan Mo Ako Please v0.1.0
            .container.nav-collapse


      .container-fluid

        .row-fluid
          .span12
            = bootstrap_flash
            = yield
    #push    	
    	
    %footer#footer
      .container
        %p.muted.credit &copy; Tayuan Mo Ako Please, Inc. 2014

app/views/pages/index.html.haml
= stylesheet_link_tag "grid"
.page-header
  %h1 
    Tayuan Mo Ako Please (TMAP) 
    %small http://tayuanmoakoplease.herokuapp.com

%h2 Mabitac, Laguna
%h3 Click on the map to select the area you want to assess re Hazard stuff.

%div#lands
  - @grid.each_with_index do |r, x|
    %div.row
      - r.each do |y|
        %div.land
          = link_to display_tag(@tags[x][y-1]), new_inquiry_path(x: x + 1, y: y)